apiVersion: v1
kind: Service
metadata:
  name: custom-service
  namespace: prod
spec:
  selector:
    app: color
  ports:
    - protocol: TCP
      port: 5000      
      targetPort: 5000
  type: ClusterIP   
