apiVersion: v1
kind: Service
metadata:
  name: color
  namespace: prod

spec:
  selector:
    app: color
  ports:
    - protocol: "tcp"
      port: 5000
      targetPort: 5000
    ClusterIP: None 
    